# SPDX-License-Identifier: GPL-2.0

dtbo-$(CONFIG_EXYNOS9611_A51) += \
	exynos9611-a51_eur_open_00.dtbo \
	exynos9611-a51_eur_open_01.dtbo \
	exynos9611-a51_eur_open_03.dtbo \
	exynos9611-a51_eur_open_07.dtbo

dtbo-$(CONFIG_EXYNOS9611_F41) += \
	exynos9611-f41_swa_open_00.dtbo

dtbo-$(CONFIG_EXYNOS9611_M21) += \
	exynos9611-m21_swa_open_00.dtbo \
	exynos9611-m21_swa_open_06.dtbo

dtbo-$(CONFIG_EXYNOS9611_M31) += \
	exynos9611-m31_eur_open_00.dtbo \
	exynos9611-m31_eur_open_01.dtbo

dtbo-$(CONFIG_EXYNOS9611_M31S) += \
	exynos9611-m31s_eur_open_00.dtbo

always		:= $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtbo
